apiVersion: v1
kind: Pod
metadata:
  name: pi-blinkt
  labels:
    zone: pi-blinkt
    version: v1
spec:
  containers:
  - name: pi-blinkt
    image: asalilje/pi-blinkt:latest
    ports:
    - containerPort: 3200